name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Обновил до v4
     
    - name: Build APK with Buildozer
      uses: uoau/buildozer-action@master
      with:
        buildozer-version: stable
        work-dir: ./
        build-target: android debug
       
    - name: Upload APK
      uses: actions/upload-artifact@v4  # Обновил до v4
      with:
        name: graphing-app-apk
        path: bin/*.apk
        retention-days: 30  # Добавил срок хранения
